server:
  port: 8080

youchat:
  netty-server:
    threads: 128 #business线程池数量
  idle:
    timeout: 120 #连接读写空闲时间（s），超时则断开连接
  httpObjectAggregator:
    maxContentLength: 1024*64
  WebSocketServerProtocolHandler:
    websocketPath: / #客户端访问路由





